<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>loana</ToolCommandName>
    <Optimize>True</Optimize>
    <Tailcalls>True</Tailcalls>
    <WarningsAsErrors>FS3569</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CLI\AnsiCodes.fs" />
    <Compile Include="CLI\MenuRender.fs" />
    <Compile Include="CLI\PanelRender.fs" />
    <Compile Include="CLI\Keymap.fs" />
    <Compile Include="CLI\CommandBuffer.fs" />
    <Compile Include="CLI\TextBuffer.fs" />
    <Compile Include="CLI\UIContext.fs" />
    <Compile Include="Study\CardSide.fs" />
    <Compile Include="Study\Cards.fs" />
    <Compile Include="Study\ScheduleResultExtensions.fs" />
    <Compile Include="Study\StudyCardSource.fs" />
    <Compile Include="Study\StudySessionState.fs" />
    <Compile Include="Study\StudySessionCommands.fs" />
    <Compile Include="Study\StudySession.fs" />
    <Compile Include="Browser\Tabs\SearchTab.fs" />
    <Compile Include="Browser\Tabs\WordlistTab.fs" />
    <Compile Include="Browser\Tabs\WordlistGroupsTab.fs" />
    <Compile Include="Browser\Tabs\ErrorsTab.fs" />
    <Compile Include="Browser\VocabExtensions.fs" />
    <Compile Include="Browser\BrowserState.fs" />
    <Compile Include="Browser\SearchTabCommands.fs" />
    <Compile Include="Browser\WordlistTabCommands.fs" />
    <Compile Include="Browser\WordlistGroupsTabCommands.fs" />
    <Compile Include="Browser\BrowserCommands.fs" />
    <Compile Include="Browser\BrowserView.fs" />
    <Compile Include="Quizzes\QuizSession.fs" />
    <Compile Include="Quizzes\AnnotationTreeRenderer.fs" />
    <Compile Include="Quizzes\Shared.fs" />
    <Compile Include="Quizzes\Articles.fs" />
    <Compile Include="Quizzes\Pronouns.fs" />
    <Compile Include="Quizzes\Quizzes.fs" />
    <Compile Include="Menu\MenuState.fs" />
    <Compile Include="Menu\MenuCommands.fs" />
    <Compile Include="Menu\MenuView.fs" />
    <Compile Include="MysteriousFlame.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Loana\Loana.fsproj" />
  </ItemGroup>
</Project>