<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
	<PublishTrimmed>True</PublishTrimmed>
	<PublishAot>True</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <Tailcalls>True</Tailcalls>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CLI\Console.fs" />
    <Compile Include="CLI\StudySession.fs" />
    <Compile Include="CLI\QuizSession.fs" />
    <Compile Include="Language\Vocab.fs" />
    <Compile Include="Language\Annotations.fs" />
    <Compile Include="Language\Declension\Deutsch.fs" />
    <Compile Include="Language\Declension\English.fs" />
    <Compile Include="Language\VerbInflections.fs" />
    <Compile Include="Language\VerbDownloader.fs" />
    <Compile Include="Data\ReviewSchedule.fs" />
    <Compile Include="Data\Words.fs" />
    <Compile Include="Data\Verbs.fs" />
    <Compile Include="Quizzes\Shared.fs" />
    <Compile Include="Quizzes\Articles.fs" />
    <Compile Include="Quizzes\Pronouns.fs" />
    <Compile Include="Quizzes\Quizzes.fs" />
    <Compile Include="Vocab\ReviewSession.fs" />
    <Compile Include="Vocab\VocabCards.fs" />
    <Compile Include="Vocab\VocabDeck.fs" />
    <Compile Include="Verbs\VerbSession.fs" />
    <Compile Include="Verbs\VerbCards.fs" />
    <Compile Include="Verbs\VerbCache.fs" />

    <Compile Include="Menu.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
